### ISSUE TITLE
specify default catalog in configuration

### ISSUE THREAD

**Issue by rabernat** [ContinuumIO/intake#190]
I would like to specify a default catalog in `~/.intake/conf.yaml`. But I can't figure out what syntax to use. The docs on the configuration file are missing an example: https://intake.readthedocs.io/en/latest/tools.html#configuration

Any hints?

**Comment by martindurant** [comment]
Yes, I see this is not clear; I have updated the doc example. It should be a list of directories in which the catalog files live, which must have extensions .yaml or .yml .

**Comment by rabernat** [comment]
Can we not just specify a catalog url directly?

**Comment by martindurant** [comment]
As currently written no. You'd like to reference a remote file?

**Comment by martindurant** [comment]
The following patch would fix specific files and remote:
```
--- a/intake/catalog/default.py
+++ b/intake/catalog/default.py
@@ -98,8 +98,11 @@ def load_combo_catalog():
         cat_dirs.append(global_dir + '/*.yaml')
         cat_dirs.append(global_dir + '/*.yml')
     for path_dir in conf.get('catalog_path', []):
-        if os.path.isdir(path_dir) and path_dir != '':
-            cat_dirs.append(path_dir + '/*.yaml')
-            cat_dirs.append(path_dir + '/*.yml')
+        if path_dir != '':
+            if not path_dir.endswith(('yaml', 'yml')):
+                cat_dirs.append(path_dir + '/*.yaml')
+                cat_dirs.append(path_dir + '/*.yml')
+            else:
+                cat_dirs.append(path_dir)
```

**Comment by rabernat** [comment]
Just the standard pangeo thing where the catalog is a remote http url.

**Comment by martindurant** [comment]
I pushed it in. If you reinstall now, should work as you expect - which, in hindsight, I ought to have seen as the obvious use case!

**Comment by rabernat** [comment]
Thanks @martindurant! I still don't understand what exactly my config file should look like.

When I go to the [latest docs](https://intake.readthedocs.io/en/latest/tools.html#configuration), I see the following:

> At present, the configuration file might look as follows:

Bu there is no example following.

Could you provide an example `config.yaml` file which specifies a default catalog? (Either here in this issue or in the docs)

**Comment by martindurant** [comment]
Sorry, it was there, but didn't render. Should come up now. The correct syntax is:

```yaml
catalog_path:
  - /home/myusername/special_dir
```
i.e., a list of directories or files (files are recognised by ending with "yaml" or "yml")

**Comment by rabernat** [comment]
I am now working from the latest master ('0.2.9+1.g8560165'). I have the following `.intake/catalog.yaml` file:
```
catalog_path:
  - 'https://github.com/pangeo-data/pangeo/raw/master/gce/catalog.yaml'
```

I do the following
```python
import
list(intake.cat)
```
and don't see any datasets

Instead, if I do
```
catalog_url = 'https://github.com/pangeo-data/pangeo/raw/master/gce/catalog.yaml'
cat = intake.Catalog(catalog_url)
list(cat)
```
I see all my datasets.

Am I doing something wrong?

**Comment by martindurant** [comment]
Instead of `.intake/catalog.yaml`, should have been `.intake/conf.yaml`

**Comment by rabernat** [comment]
Great, it works!
